feat: added unit tests for header
bgwebagency/redesigner.io pull request #61
Opened 2023-06-26 09:19 UTC by baranero

2023-06-26 09:22 UTC, baranero commented
I had an issues with commit. I changed husky configuration. Commit works if you will do it like this way:
`npm run format`
`git add .`
`git commit -m "<type>: <subject>"`
`gir push origin <branch-name>`

2023-06-28 19:18 UTC, lausuarez02 commented on app/components/Header/Header.tsx
> +							aria-label="sun"
I would add formatting here but for now it's good enough

2023-06-28 19:18 UTC, lausuarez02 commented on package.json
> +		"prettier-check": "prettier --check \"**/*.+(js|json|ts|jsx|tsx)\"",
I do not understand how you add the prettier-check library but it doesnt have been formatting

2023-06-28 19:19 UTC, lausuarez02 requested changes

2023-06-28 19:19 UTC, lausuarez02 commented on app/components/Header/Header.tsx
> +							aria-label="sun"
Fomat this please. :)

2023-07-02 11:09 UTC, kirandash approved these changes
LGTM

2023-07-02 11:09 UTC, merged